/*
 * Copyright (c) 2025 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * // Some portions generated by Co-Pilot
 */

package org.eclipse.cbi.central.plugin;

import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.project.MavenProject;
import org.apache.maven.settings.Settings;
import org.apache.maven.settings.Server;
import org.apache.maven.settings.crypto.SettingsDecrypter;
import org.apache.maven.settings.crypto.SettingsDecryptionRequest;
import org.apache.maven.settings.crypto.DefaultSettingsDecryptionRequest;
import org.apache.maven.settings.crypto.SettingsDecryptionResult;
import org.apache.maven.plugin.AbstractMojo;
import org.eclipse.cbi.central.CentralPortalClient;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Abstract base class for Central Portal Maven Mojos.
 * Handles common configuration and client initialization.
 */
public abstract class AbstractCentralMojo extends AbstractMojo {

    /**
     * The bearer token used for authentication with the Central Portal API.
     */
    @Parameter(property = "central.bearerToken")
    protected String bearerToken;

    /**
     * The server ID used to retrieve credentials from settings.xml.
     */
    @Parameter(property = "central.serverId", defaultValue = "central")
    protected String serverId;

    /**
     * Whether to automatically build the bearer token from username:password in
     * settings.xml.
     * When true, the bearer token is created by base64 encoding "username:password"
     * from the server entry.
     */
    @Parameter(property = "central.bearerCreate", defaultValue = "false")
    protected boolean bearerCreate;

    /**
     * The Central Portal API URL. If not set, the default is used.
     */
    @Parameter(property = "central.centralApiUrl")
    protected String centralApiUrl;

    /**
     * If true, drop all deployments in the namespace.
     */
    @Parameter(property = "central.removeAll", defaultValue = "false")
    protected boolean removeAll;

    /**
     * If true, only drop deployments in FAILED state (used with removeAll).
     */
    @Parameter(property = "central.removeFailedOnly", defaultValue = "true")
    protected boolean removeFailedOnly;

    /**
     * The Maven settings instance, used to retrieve server credentials.
     */
    @Parameter(defaultValue = "${settings}", readonly = true)
    protected Settings settings;

    /**
     * The Maven settings decrypter for decrypting encrypted passwords.
     */
    @Component
    protected SettingsDecrypter settingsDecrypter;

    /**
     * The Maven project instance for this execution.
     */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    protected MavenProject project;

    /**
     * HTTP connection timeout in seconds.
     */
    @Parameter(property = "central.connectTimeout", defaultValue = "30")
    protected int connectTimeout;

    /**
     * HTTP read timeout in seconds (for receiving responses).
     */
    @Parameter(property = "central.readTimeout", defaultValue = "300")
    protected int readTimeout;

    /**
     * HTTP write timeout in seconds (for sending requests).
     */
    @Parameter(property = "central.writeTimeout", defaultValue = "300")
    protected int writeTimeout;

    /**
     * The CentralPortalClient instance used for API interactions.
     */
    protected CentralPortalClient client;

    /**
     * Retrieves the bearer token for authentication. Checks the parameter, then
     * settings.xml server entry.settings
     *
     * @return the bearer token string
     * @throws IllegalArgumentException if no token is found
     */
    protected String getBearerToken() {
        if (this.bearerToken != null && !this.bearerToken.isEmpty()) {
            getLog().info("Using provided bearer token from parameter -Dcentral.bearerToken.");
            return this.bearerToken;
        }
        if (this.settings != null) {
            Server server = this.settings.getServer(this.serverId);
            if (server != null) {
                // Decrypt the server credentials if encrypted
                Server decryptedServer = decryptServer(server);

                // If bearerCreate is true, build the token from username:password
                if (this.bearerCreate) {
                    String username = decryptedServer.getUsername();
                    String password = decryptedServer.getPassword();
                    getLog().info("Building bearer token from username(" + username
                            + "):password in settings.xml server entry: "
                            + this.serverId);
                    if (username != null && !username.isEmpty() && password != null && !password.isEmpty()) {
                        String credentials = username + ":" + password;
                        return Base64.getEncoder().encodeToString(credentials.getBytes(StandardCharsets.UTF_8));
                    } else {
                        String missingFields = null;
                        if (username == null || username.isEmpty()) {
                            missingFields = "username";
                        }
                        if (password == null || password.isEmpty()) {
                            if (missingFields != null) {
                                missingFields += " and password are missing";
                            } else {
                                missingFields = "password is missing";
                            }
                        } else {
                            missingFields += " is missing";
                        }

                        throw new IllegalArgumentException(
                                "central.bearerCreate is true but " + missingFields
                                        + " in settings.xml server '"
                                        + this.serverId + "'.");
                    }
                } else {
                    // Otherwise, use the password field as the bearer token directly
                    if (decryptedServer.getPassword() != null && !decryptedServer.getPassword().isEmpty()) {
                        getLog().info("Using bearer token from settings.xml server entry: " + this.serverId);
                        return decryptedServer.getPassword();
                    } else {
                        throw new IllegalArgumentException(
                                "Bearer token is missing in field password in settings.xml server '" + this.serverId
                                        + "'.");
                    }
                }
            } else {
                getLog().warn("No server entry found in settings.xml for id: " + this.serverId);
            }
        } else {
            getLog().warn("Maven settings instance is null; cannot retrieve server credentials.");
        }
        throw new IllegalArgumentException(
                "Bearer token must be provided via -Dcentral.bearerToken or settings.xml server '" + this.serverId
                        + "'.");
    }

    /**
     * Decrypts the server credentials if they are encrypted.
     *
     * @param server the server to decrypt
     * @return the decrypted server
     */
    private Server decryptServer(Server server) {
        if (this.settingsDecrypter != null) {
            getLog().info("Decrypting server credentials for server id: " + this.serverId);
            SettingsDecryptionRequest request = new DefaultSettingsDecryptionRequest(server);
            SettingsDecryptionResult result = this.settingsDecrypter.decrypt(request);
            if (!result.getProblems().isEmpty()) {
                result.getProblems().forEach(p ->
                    getLog().warn("Problem decrypting credentials for server '" + this.serverId + "': "
                        + p.getMessage(), p.getException()));
            }
            Server decryptedServer = result.getServer();
            return decryptedServer != null ? decryptedServer : server;
        } else {
            getLog().info("SettingsDecrypter is not available; returning server without decryption.");
        }
        return server;
    }

    /**
     * Initializes the CentralPortalClient using the bearer token and optional API
     * URL.
     */
    protected void initClient() {
        client = centralApiUrl != null && !centralApiUrl.isEmpty()
                ? new CentralPortalClient(getBearerToken(), centralApiUrl, connectTimeout, readTimeout, writeTimeout)
                : new CentralPortalClient(getBearerToken(), null, connectTimeout, readTimeout, writeTimeout);
    }
}
